name = "svelte-atproto-oauth-cloudflare-workers"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "OAUTH_SESSIONS"
id = "c44fc97274b84f5a97a8399b1977ad0d"

[[kv_namespaces]]
binding = "OAUTH_STATES"
id = "115d8089d9ca4592a3a5e4a7d9146610"
